name: CI/CD
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Scala using Coursier
        uses: coursier/setup-action@v1
        with:
          apps: sbt

      - name: Scalafmt
        run: sbt scalafmtCheckAll

      - name: Run tests
        run: sbt coverage test

      - name: Coverage Report
        run: sbt coverageAggregate

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
